@php($logo=public_path('img/logo-caminos-ra.png'))
<!doctype html><html><head><meta charset="utf-8"><style>
@page{margin:18px 16px} body{font-family:DejaVu Sans;font-size:6px;color:#222}.head{display:flex;align-items:center;border-bottom:2px solid #0b3d62;padding-bottom:6px}.logo{width:48px;height:auto;margin-right:10px}.title{font-size:13px;color:#0b3d62;font-weight:bold}.sub{font-size:7px}.t{width:100%;border-collapse:collapse;margin-top:8px}.t th,.t td{border:1px solid #aaa;padding:2px}.t th{background:#0b3d62;color:#fff;text-align:center}.group{background:#eef3f7;font-weight:bold}.r{text-align:right}.c{text-align:center}.section{font-size:9px;color:#0b3d62;font-weight:bold;margin-top:12px}.foot{margin-top:8px;font-size:6px;color:#667788}
</style></head><body>
<div class="head">@if(file_exists($logo))<img class="logo" src="data:image/png;base64,{{ base64_encode(file_get_contents($logo)) }}">@endif<div><div class="title">INVENTARIO MENSUAL – {{ strtoupper($cierreMensual->almacen) }}</div><div class="sub">Periodo: {{ $cierreMensual->fecha_desde->format('d/m/Y') }} al {{ $cierreMensual->fecha_hasta->format('d/m/Y') }} · Cierre {{ $cierreMensual->estado }}</div></div></div>
<table class="t"><thead><tr><th rowspan="2">Partida</th><th rowspan="2">Código actual / LINAME</th><th rowspan="2">Descripción y concentración</th><th rowspan="2">Forma farmacéutica</th><th colspan="3">SALDO ANTERIOR</th><th colspan="3">INGRESOS<br>Transferencias entre regionales</th><th colspan="3">INGRESOS<br>Compras locales</th><th colspan="3">TOTAL INGRESOS</th><th colspan="2">EGRESO<br>Regional</th><th colspan="3">SALDO DEL MES<br>al {{ $cierreMensual->fecha_hasta->format('d/m/Y') }}</th></tr><tr>@for($i=0;$i<4;$i++)<th>Cant.</th><th>P. Unit.</th><th>Importe</th>@endfor<th>Cant.</th><th>Importe</th><th>Cant.</th><th>P. Unit.</th><th>Importe</th></tr></thead><tbody>
@foreach($detalles as $d)<tr><td>{{ $d->partida_codigo }}</td><td>{{ $d->codigo }}</td><td>{{ $d->descripcion }}</td><td>{{ $d->forma_farmaceutica }}</td><td class="r">{{ $d->saldo_anterior_cantidad }}</td><td class="r">{{ number_format($d->saldo_anterior_precio,2,',','.') }}</td><td class="r">{{ number_format($d->saldo_anterior_importe,2,',','.') }}</td><td class="r">{{ $d->transferencia_cantidad }}</td><td class="r">{{ number_format($d->transferencia_precio,2,',','.') }}</td><td class="r">{{ number_format($d->transferencia_importe,2,',','.') }}</td><td class="r">{{ $d->compra_local_cantidad }}</td><td class="r">{{ number_format($d->compra_local_precio,2,',','.') }}</td><td class="r">{{ number_format($d->compra_local_importe,2,',','.') }}</td><td class="r">{{ $d->total_ingresos_cantidad }}</td><td class="r">{{ number_format($d->total_ingresos_precio,2,',','.') }}</td><td class="r">{{ number_format($d->total_ingresos_importe,2,',','.') }}</td><td class="r">{{ $d->egreso_cantidad }}</td><td class="r">{{ number_format($d->egreso_importe,2,',','.') }}</td><td class="r">{{ $d->saldo_mes_cantidad }}</td><td class="r">{{ number_format($d->saldo_mes_precio,2,',','.') }}</td><td class="r">{{ number_format($d->saldo_mes_importe,2,',','.') }}</td></tr>@endforeach
</tbody></table>
<div class="section">RESUMEN CUENTA 121 – MEDICAMENTOS E INSUMOS MÉDICOS</div><table class="t"><thead><tr><th>Grupo</th><th>Saldo anterior</th><th>Ingresos transferencias</th><th>Ingresos compras locales</th><th>Total ingresos</th><th>Egresos</th><th>Saldo del mes</th></tr></thead><tbody>@foreach($resumen as $r)<tr><td>{{ $r['grupo'] }}</td><td class="r">{{ number_format($r['saldo_anterior_importe'],2,',','.') }}</td><td class="r">{{ number_format($r['transferencia_importe'],2,',','.') }}</td><td class="r">{{ number_format($r['compra_local_importe'],2,',','.') }}</td><td class="r">{{ number_format($r['total_ingresos_importe'],2,',','.') }}</td><td class="r">{{ number_format($r['egreso_importe'],2,',','.') }}</td><td class="r">{{ number_format($r['saldo_mes_importe'],2,',','.') }}</td></tr>@endforeach</tbody></table>
<div class="foot">Generado por el Sistema de Gestión de Almacén · Cerrado por {{ $cierreMensual->usuario?->name ?? 'Sin usuario' }} · {{ optional($cierreMensual->cerrado_en)->format('d/m/Y H:i') }}</div></body></html>
