<template>
  <form class="card shadow-sm border-0 mb-5" @submit.prevent="registrar">
    <div class="card-header bg-soft-blue border-0 py-3"><h5 class="mb-0 text-primary">Nota de ingreso al almacén</h5><small class="text-muted">Seleccione productos del catálogo institucional; los datos maestros no se editan aquí.</small></div>
    <div class="card-body p-4">
      <div v-if="mensaje" class="alert alert-success">{{ mensaje }} <button v-if="pdfId" type="button" class="btn btn-link p-0 ms-2 align-baseline" @click="descargarPdf">Abrir PDF</button></div><div v-if="errorGeneral" class="alert alert-danger">{{ errorGeneral }}</div>
      <h6 class="text-csc-orange border-bottom pb-2">Encabezado de la nota</h6>
      <div class="row g-3 mb-4"><div class="col-md-4"><label>Almacén *</label><input v-model.trim="form.ingreso.almacen" class="form-control"></div><div class="col-md-4"><label>Procedencia / proveedor *</label><input v-model.trim="form.proveedor.nombre" class="form-control"></div><div class="col-md-4"><label>Teléfono proveedor</label><input v-model.trim="form.proveedor.telefono" class="form-control"></div><div class="col-md-3"><label>Fecha *</label><input v-model="form.ingreso.fecha_ingreso" type="date" class="form-control"></div><div class="col-md-3"><label>N.º de remisión</label><input v-model.trim="form.ingreso.numero_remision" class="form-control"></div><div class="col-md-3"><label>N.º de factura</label><input v-model.trim="form.ingreso.numero_factura" class="form-control"></div><div class="col-md-3"><label>Tipo *</label><select v-model="form.ingreso.tipo_ingreso" class="form-select"><option value="compra_local">Compra local</option><option value="transferencia">Transferencia</option><option value="donacion">Donación</option><option value="devolucion">Devolución</option><option value="otro">Otro</option></select></div></div>
      <div class="d-flex justify-content-between align-items-center border-bottom pb-2 mb-3"><h6 class="text-csc-orange mb-0">Detalle de ítems</h6><button type="button" class="btn btn-outline-primary btn-sm" @click="agregarItem">+ Agregar ítem</button></div>
      <div class="table-responsive"><table class="table table-sm table-bordered align-middle detalle"><thead class="table-light"><tr><th>Buscar producto *</th><th>Partida</th><th>LINAME</th><th>Descripción / concentración</th><th>Forma / unidad</th><th>Lote *</th><th>Vencimiento</th><th>Cant. *</th><th>P. unitario *</th><th>Importe</th><th></th></tr></thead><tbody><tr v-for="(item, indice) in form.items" :key="indice"><td class="position-relative"><input v-model.trim="item.busqueda" class="form-control form-control-sm" placeholder="Nombre o código" @input="buscarProductos(item)" @focus="buscarProductos(item)"><div v-if="item.resultados.length" class="lista-resultados shadow"><button v-for="producto in item.resultados" :key="producto.id" type="button" class="list-group-item list-group-item-action" @click="seleccionarProducto(item, producto)"><strong>{{ producto.codigo }}</strong> - {{ producto.nombre }} {{ producto.concentracion }}<small class="d-block">{{ producto.partida_presupuestaria?.codigo }} · {{ producto.forma_farmaceutica }}</small></button></div></td><td>{{ item.producto?.partida_presupuestaria?.codigo || '—' }}</td><td>{{ item.producto?.codigo || '—' }}</td><td>{{ item.producto ? `${item.producto.nombre} ${item.producto.concentracion || ''}` : '—' }}</td><td>{{ item.producto ? `${item.producto.forma_farmaceutica || '—'} / ${item.producto.unidad_presentacion || '—'}` : '—' }}</td><td><input v-model.trim="item.lote.codigo_lote" class="form-control form-control-sm" placeholder="Lote o procedencia"></td><td><input v-model="item.lote.fecha_vencimiento" type="date" class="form-control form-control-sm"></td><td><input v-model.number="item.cantidad" type="number" min="1" class="form-control form-control-sm"></td><td><input v-model.number="item.precio_unitario" type="number" min="0" step="0.01" class="form-control form-control-sm"></td><td class="text-end fw-bold">{{ moneda(totalItem(item)) }}</td><td><button v-if="form.items.length > 1" type="button" class="btn btn-outline-danger btn-sm" @click="form.items.splice(indice,1)">×</button></td></tr></tbody></table></div>
      <div class="row justify-content-end"><div class="col-md-5 text-end"><div class="fs-5 fw-bold">Total: {{ moneda(totalGeneral) }}</div><small class="text-uppercase text-muted">{{ totalLiteral }} bolivianos</small></div></div>
      <div class="row g-3 mt-2"><div class="col-md-6"><label>Recibido por *</label><input v-model.trim="form.ingreso.recibido_por" class="form-control"></div><div class="col-md-6"><label>Autorizado por *</label><input v-model.trim="form.ingreso.autorizado_por" class="form-control"></div><div class="col-12"><label>Observaciones</label><textarea v-model.trim="form.ingreso.observacion" class="form-control" rows="2"></textarea></div></div>
    </div><div class="card-footer bg-white p-4 text-end"><button class="btn btn-csc-orange px-5 fw-bold" :disabled="procesando">{{ procesando ? 'Guardando…' : 'Registrar nota de ingreso' }}</button></div>
  </form>
</template>
<script setup>
import axios from 'axios'; import { computed, ref } from 'vue';
const props = defineProps({ recibidoPor: { type: String, default: '' } }); const nuevoItem = () => ({ producto_id: null, producto: null, busqueda: '', resultados: [], lote: { codigo_lote: '', fecha_vencimiento: '' }, cantidad: 1, precio_unitario: 0 }); const nuevoFormulario = () => ({ proveedor: { nombre: '', telefono: '' }, ingreso: { almacen: 'REGIONAL LA PAZ', fecha_ingreso: new Date().toISOString().slice(0,10), numero_remision: '', numero_factura: '', tipo_ingreso: 'compra_local', observacion: '', recibido_por: props.recibidoPor, autorizado_por: 'CAJA NACIONAL DE CAMINOS' }, items: [nuevoItem()] }); const form = ref(nuevoFormulario()), procesando = ref(false), mensaje = ref(''), errorGeneral = ref(''), pdfId = ref(null); let timer;
const buscarProductos = item => { clearTimeout(timer); if (item.busqueda.length < 2) { item.resultados=[]; return; } timer = setTimeout(async () => { const { data } = await axios.get('api/medicamentos', { params: { buscar: item.busqueda } }); item.resultados=data; }, 250); }; const seleccionarProducto = (item,p) => { item.producto_id=p.id; item.producto=p; item.busqueda=`${p.codigo} - ${p.nombre} ${p.concentracion || ''}`; item.resultados=[]; }; const agregarItem=()=>form.value.items.push(nuevoItem()); const totalItem=i=>(Number(i.cantidad)||0)*(Number(i.precio_unitario)||0); const totalGeneral=computed(()=>form.value.items.reduce((sum,i)=>sum+totalItem(i),0)); const moneda=n=>new Intl.NumberFormat('es-BO',{style:'currency',currency:'BOB'}).format(n); const totalLiteral=computed(()=>`${Math.floor(totalGeneral.value)} con ${String(Math.round((totalGeneral.value%1)*100)).padStart(2,'0')}/100`);
const descargarPdf = async () => { const { data } = await axios.get(`api/ingresos/${pdfId.value}/pdf`, { responseType: 'blob' }); const url = URL.createObjectURL(new Blob([data], { type: 'application/pdf' })); window.open(url, '_blank'); setTimeout(() => URL.revokeObjectURL(url), 60000); }; const registrar=async()=>{ procesando.value=true; mensaje.value='';errorGeneral.value='';pdfId.value=null;try{const {data}=await axios.post('api/ingresos',form.value);mensaje.value=data.message;pdfId.value=data.pdf_id;form.value=nuevoFormulario();}catch(e){errorGeneral.value=e.response?.data?.message||'Revise los campos obligatorios y seleccione un producto de catálogo en cada fila.';}finally{procesando.value=false;}};
</script><style scoped>.detalle{min-width:1400px}.lista-resultados{position:absolute;z-index:10;top:100%;left:0;right:0;max-height:220px;overflow:auto;background:#fff;border:1px solid #ddd}.lista-resultados button{font-size:.8rem;text-align:left}.detalle th{white-space:nowrap}</style>
