<template>
  <section class="reports-page">
    <div class="reports-hero"><h2>Reportes y documentos</h2><p>Genere nuevamente documentos históricos y reportes del almacén.</p></div>
    <div class="report-grid">
      <article class="report-card"><div class="report-title">Notas de ingreso</div><p>Busque por N.º de nota o documento de remisión. Puede descargar PDF o Excel.</p><input v-model="busIngreso" @input="cargarIngresos" class="form-control" placeholder="Ej.: N.º 000001 o remisión"><div class="results"> <div v-for="i in ingresos" :key="i.id" class="result-row"><div><strong>{{i.numero_nota}}</strong><span>{{i.proveedor || 'Sin proveedor'}} · {{i.fecha}}<template v-if="i.numero_remision"> · Remisión: {{i.numero_remision}}</template></span></div><div><button class="btn-orange" @click="descargar('api/ingresos/'+i.id+'/pdf')">PDF</button><button class="btn-outline" @click="descargar('api/reportes/ingresos/'+i.id+'/excel')">Excel</button></div></div><div v-if="busIngreso && !ingresos.length" class="empty">Sin coincidencias.</div></div></article>
      <article class="report-card"><div class="report-title">Notas de salida</div><p>Busque por número de salida o pedido. Puede descargar PDF o Excel.</p><input v-model="busSalida" @input="cargarSalidas" class="form-control" placeholder="Ej.: 12 o N.º pedido"><div class="results"><div v-for="s in salidas" :key="s.id" class="result-row"><div><strong>Salida N.º {{s.numero_salida}}</strong><span>{{s.destino || 'Sin destino'}} · {{s.fecha}}<template v-if="s.numero_pedido"> · Pedido: {{s.numero_pedido}}</template></span></div><div><button class="btn-orange" @click="descargar('api/reportes/salidas/'+s.id+'/pdf')">PDF</button><button class="btn-outline" @click="descargar('api/reportes/salidas/'+s.id+'/excel')">Excel</button></div></div></div></article>
      <article class="report-card report-wide"><div class="report-title">Reporte de inventario</div><p>Busque y agregue uno o varios productos para generar un reporte específico, o genere el inventario completo.</p>
<div class="filter-row"><div class="search-wrap"><input v-model="inv.buscar" @input="buscarInventarioProductos" class="form-control" placeholder="Buscar producto / LINAME para agregar"><div v-if="invSugerencias.length" class="suggestions"><button v-for="p in invSugerencias" :key="p.id" @click="seleccionarInventarioProducto(p)"><strong>{{p.codigo}}</strong> — {{p.nombre}}</button></div></div></div>
<div v-if="productosInventario.length" class="inventory-selection"><div class="inventory-head"><strong>Productos seleccionados para el reporte</strong><span>{{productosInventario.length}} producto(s)</span></div><div class="inventory-table-wrap"><table class="inventory-table"><thead><tr><th>LINAME / Código</th><th>Producto</th><th>Partida</th><th>Acciones</th></tr></thead><tbody><tr v-for="(p,index) in productosInventario" :key="p.id"><td>{{p.codigo}}</td><td v-if="editandoInventario!==index">{{p.nombre}}</td><td v-else><input v-model="edicionInventario.nombre" class="table-input"></td><td>{{p.partida_presupuestaria?.codigo || p.partida || '—'}}</td><td class="table-actions"><button class="edit-btn" @click="editarInventario(index)">{{editandoInventario===index?'Guardar':'Editar'}}</button><button class="delete-btn" @click="eliminarInventario(index)">Eliminar</button></td></tr></tbody></table></div></div>
<div class="actions" v-if="productosInventario.length"><button class="btn-orange" @click="generarSeleccionados('pdf')">Generar PDF seleccionados</button><button class="btn-outline" @click="generarSeleccionados('excel')">Generar EXCEL seleccionados</button></div>
<div class="complete-actions"><strong>Inventario completo</strong><span>Incluye todos los productos registrados en el inventario al momento de generar el reporte.</span><div class="actions"><button class="btn-orange" @click="descargar('api/reportes/inventario/pdf')">Generar inventario completo PDF</button><button class="btn-outline" @click="descargar('api/reportes/inventario/excel')">Generar inventario completo EXCEL</button></div></div></article>
      <article class="report-card report-wide"><div class="report-title">Kardex por producto</div><p>Seleccione un producto y, opcionalmente, un rango de fechas.</p><div class="filter-row"><div class="search-wrap"><input v-model="textoProducto" @input="buscarProductos" class="form-control" placeholder="Buscar por LINAME o nombre"><div v-if="sugerencias.length" class="suggestions"><button v-for="p in sugerencias" :key="p.id" @click="seleccionarProducto(p)"><strong>{{p.codigo}}</strong> — {{p.nombre}}</button></div></div><input v-model="desde" type="date" class="form-control"><input v-model="hasta" type="date" class="form-control"></div><div class="selected" v-if="producto">{{producto.codigo}} — {{producto.nombre}}</div><div class="actions"><button class="btn-orange" :disabled="!producto" @click="descargar('api/reportes/kardex/pdf',{producto_id:producto?.id,desde,hasta})">Generar Kardex PDF</button></div></article>
    </div>
  </section>
</template>
<script setup>
import axios from 'axios'; import {reactive,ref,onMounted} from 'vue';
const ingresos=ref([]),salidas=ref([]),busIngreso=ref(''),busSalida=ref(''),textoProducto=ref(''),sugerencias=ref([]),producto=ref(null),desde=ref(''),hasta=ref(''),invSugerencias=ref([]); const inv=reactive({buscar:''}),productosInventario=ref([]),editandoInventario=ref(null),edicionInventario=reactive({nombre:''}); let ti,ts,tp,tinv;
const cargarIngresos=()=>{clearTimeout(ti);ti=setTimeout(async()=>{ingresos.value=(await axios.get('api/reportes/ingresos',{params:{buscar:busIngreso.value}})).data},250)};
const cargarSalidas=()=>{clearTimeout(ts);ts=setTimeout(async()=>{salidas.value=(await axios.get('api/reportes/salidas',{params:{buscar:busSalida.value}})).data},250)};
const buscarProductos=()=>{clearTimeout(tp);tp=setTimeout(async()=>{if(textoProducto.value.trim().length<1){sugerencias.value=[];return}sugerencias.value=(await axios.get('api/medicamentos',{params:{buscar:textoProducto.value}})).data.slice(0,8)},200)};
const seleccionarProducto=p=>{producto.value=p;textoProducto.value=`${p.codigo} — ${p.nombre}`;sugerencias.value=[]};
const buscarInventarioProductos=()=>{clearTimeout(tinv);tinv=setTimeout(async()=>{if(inv.buscar.trim().length<1){invSugerencias.value=[];return}const data=(await axios.get('api/medicamentos',{params:{buscar:inv.buscar}})).data;invSugerencias.value=(Array.isArray(data)?data:(data.data||[])).slice(0,8)},200)};
const seleccionarInventarioProducto=p=>{if(!productosInventario.value.some(x=>x.id===p.id))productosInventario.value.push({...p});inv.buscar='';invSugerencias.value=[]};
const eliminarInventario=index=>{if(editandoInventario.value===index)editandoInventario.value=null;productosInventario.value.splice(index,1)};
const editarInventario=index=>{if(editandoInventario.value===index){productosInventario.value[index].nombre=edicionInventario.nombre;editandoInventario.value=null;return}editandoInventario.value=index;edicionInventario.nombre=productosInventario.value[index].nombre};
const generarSeleccionados=formato=>{const ids=productosInventario.value.map(p=>p.id).join(',');descargar('api/reportes/inventario/'+formato,{producto_ids:ids})};
const descargar=async(url,params={})=>{const r=await axios.get(url,{params,responseType:'blob'});const type=r.headers['content-type']||'application/octet-stream';const blob=new Blob([r.data],{type});const cd=r.headers['content-disposition']||'';const match=/filename[^;=\n]*=((['"]).*?\2|[^;\n]*)/.exec(cd);let filename=match&&match[1]?match[1].replace(/['"]/g,''):'reporte';if(!/\.(pdf|xls|xlsx)$/i.test(filename)){filename+=type.includes('pdf')?'.pdf':'.xls'}const a=document.createElement('a');const objectUrl=URL.createObjectURL(blob);a.href=objectUrl;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(objectUrl),1000)};
onMounted(()=>{cargarIngresos();cargarSalidas()});
</script>
<style scoped>
.reports-page{max-width:1400px;margin:0 auto;padding:8px 0 30px}.reports-hero{background:#0b3d62;color:#fff;border-radius:14px;padding:24px 28px;margin-bottom:18px}.reports-hero h2{margin:0;font-size:1.65rem}.reports-hero p{margin:6px 0 0;opacity:.9}.report-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.report-card{background:#fff;border:1px solid #e1e7ed;border-radius:14px;padding:20px;box-shadow:0 6px 18px rgba(11,61,98,.06)}.report-wide{grid-column:1/-1}.report-title{background:#0b3d62;color:#fff;padding:10px 14px;border-radius:9px;font-weight:700;margin-bottom:12px}.results{margin-top:10px;max-height:280px;overflow:auto}.results>button{width:100%;text-align:left;border:0;border-bottom:1px solid #eee;background:#fff;padding:10px}.results span,.result-row span{display:block;font-size:.82rem;color:#667788}.result-row{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #eee;padding:9px 0}.filter-row{display:grid;grid-template-columns:2fr 1fr 1fr;gap:10px}.actions{display:flex;gap:10px;margin:14px 0}.btn-orange{background:#e85d04;color:#fff;border:0;border-radius:7px;padding:8px 14px}.btn-outline{background:#fff;color:#0b3d62;border:1px solid #0b3d62;border-radius:7px;padding:7px 12px;margin-left:6px}.search-wrap{position:relative}.suggestions{position:absolute;z-index:10;background:#fff;border:1px solid #dbe3ea;width:100%;border-radius:8px;box-shadow:0 8px 18px rgba(0,0,0,.12);max-height:220px;overflow:auto}.suggestions button{display:block;width:100%;text-align:left;background:#fff;border:0;border-bottom:1px solid #eee;padding:8px 10px}.selected{margin-top:8px;color:#0b3d62;font-weight:600}.empty{padding:10px;color:#667788}.inventory-selection{margin-top:16px;border:1px solid #dbe3ea;border-radius:10px;overflow:hidden}.inventory-head{background:#0b3d62;color:#fff;padding:10px 14px;display:flex;justify-content:space-between}.inventory-table-wrap{overflow-x:auto}.inventory-table{width:100%;border-collapse:collapse}.inventory-table th{background:#f4f7fa;color:#0b3d62}.inventory-table th,.inventory-table td{padding:10px;border-bottom:1px solid #e3e9ee;text-align:left}.table-actions{white-space:nowrap}.edit-btn,.delete-btn{border:0;border-radius:6px;padding:6px 9px;margin-right:6px}.edit-btn{background:#0b3d62;color:#fff}.delete-btn{background:#e85d04;color:#fff}.table-input{width:100%;padding:6px;border:1px solid #cdd8e2;border-radius:5px}.complete-actions{margin-top:20px;border-top:2px solid #e85d04;padding-top:14px}.complete-actions strong{display:block;color:#0b3d62;font-size:1.05rem}.complete-actions span{display:block;color:#667788;margin:4px 0}@media(max-width:850px){.report-grid{grid-template-columns:1fr}.filter-row{grid-template-columns:1fr}.report-wide{grid-column:auto}}
</style>
